In [2]:
import numpy as np

In [3]:
a = np.random.randn(5)

In [6]:
a

array([ 0.06292623, -0.51258145, -2.18309131,  0.81468514,  1.36972978])

In [4]:
print(a.shape) #rank 1 array, neither a row vector nor a column vector

(5,)


In [8]:
#non-intuitive effects
print(a.T) #looks the same as a
print(np.dot(a, a.T)) # matrix expected, we get number

[ 0.06292623 -0.51258145 -2.18309131  0.81468514  1.36972978]
7.572458669589319


In [15]:
# better to use
a1 = np.random.randn(5,1)
print("normal:" + str(a1))
print("transposed: " + str(a1.T))

normal:[[-0.93616491]
 [ 0.20775262]
 [ 0.53629684]
 [-2.07100647]
 [-1.27463486]]
transposed: [[-0.93616491  0.20775262  0.53629684 -2.07100647 -1.27463486]]


In [16]:
np.dot(a1, a1.T)

array([[ 0.87640473, -0.19449071, -0.50206228,  1.93880358,  1.19326842],
       [-0.19449071,  0.04316115,  0.11141707, -0.43025702, -0.26480873],
       [-0.50206228,  0.11141707,  0.2876143 , -1.11067422, -0.68358265],
       [ 1.93880358, -0.43025702, -1.11067422,  4.28906778,  2.63977703],
       [ 1.19326842, -0.26480873, -0.68358265,  2.63977703,  1.62469402]])

In [18]:
assert(a1.shape == (5,1))

In [19]:
assert(a.shape == (5,1))

AssertionError: 

In [20]:
a = np.random.randn(2, 3)

In [21]:
a

array([[-0.83274141, -0.5426918 ,  1.3491962 ],
       [-0.38119677,  0.57771224, -0.78588069]])

In [22]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [25]:
print(a)

[[ 1.32657613  1.67257241 -1.15683701]
 [ 0.0555749   0.2465846  -1.07225577]]


In [26]:
print(b)

[[ 1.08101608]
 [-0.43354521]]


In [23]:
c.shape

(2, 3)

In [27]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [28]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [29]:
c.shape

(12288, 45)

In [30]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [32]:
a

array([[ 0.96900903, -0.98980535,  0.37671102],
       [ 0.36854914, -0.98986106, -0.23194829],
       [ 1.02055025,  0.2072646 ,  0.16907441]])

In [33]:
b

array([[-0.17060963],
       [-0.72320846],
       [ 0.27202782]])

In [36]:
-0.98986106*-0.72320846

0.7158758928165676

In [31]:
c

array([[-0.16532227,  0.16887032, -0.06427053],
       [-0.26653786,  0.7158759 ,  0.16774697],
       [ 0.27761806,  0.05638174,  0.04599294]])